/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontFam2 = 'Custom';
  static const String? _kFontPkg = null;

  static IconData bottombarbagicon =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static  IconData date_range =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static  IconData path_3177 =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static  IconData path_4346 =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static  IconData group_2369 =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static  IconData usericon =
      IconData(0xe805, fontFamily: _kFontFam2, fontPackage: _kFontPkg);
}
